### ISSUE TITLE
Code refactoring (Task list)

### ISSUE THREAD

**Issue by MSenso** [catebi/FreeganBot#65]
- [x] Create utils module #72
- [x] Create text processing module #73 
- [x] Create catebi api module #74 
- [x] Create telegram api module #75
